// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL?.trim();
const SUPABASE_ANON_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY?.trim();

// Validate URL and key format
const isValidSupabaseUrl = SUPABASE_URL?.match(/^https:\/\/[a-z0-9-]+\.supabase\.co$/i);
const isValidAnonKey = SUPABASE_ANON_KEY?.match(/^ey[A-Za-z0-9-_]+\.[A-Za-z0-9-_]+\.[A-Za-z0-9-_]+$/);

// Debug configuration
console.log('Supabase Configuration:', {
  url: SUPABASE_URL,
  key: SUPABASE_ANON_KEY?.substring(0, 10) + '...',
  urlValid: !!isValidSupabaseUrl,
  keyValid: !!isValidAnonKey,
  envKeys: Object.keys(import.meta.env).filter(key => key.startsWith('VITE_')),
});

if (!SUPABASE_URL || !SUPABASE_ANON_KEY) {
  throw new Error('Missing Supabase environment variables. Please check your .env.local file.');
}

if (!isValidSupabaseUrl) {
  throw new Error('Invalid Supabase URL format. URL should be like: https://your-project.supabase.co');
}

if (!isValidAnonKey) {
  throw new Error('Invalid Supabase anon key format. Key should be a JWT token starting with "ey"');
}

// Create Supabase client with additional options for better error handling
export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_ANON_KEY, {
  auth: {
    autoRefreshToken: true,
    persistSession: true,
    detectSessionInUrl: true
  }
});