// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ufywpifbqbzampiiuetc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVmeXdwaWZicWJ6YW1waWl1ZXRjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzczNjgxNjYsImV4cCI6MjA1Mjk0NDE2Nn0.7tjain_I8jJ2Nc3AdurDOniMKE6mEM_Edu_M-mi2eCI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);